name: C/C++ CI

on: [push]

jobs:
  clang-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Debug Compile
      run: |
        mkdir build
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S . -B ./build
        make --directory ./build -j

    - name: Debug Tests
      run: make test -C ./build ARGS='--output-on-failure'
    
    - name: Clean Build
      run: |
       rm -rf ./build/
    
    - name: Release Compile
      run: |
        mkdir build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S . -B ./build
        make --directory ./build -j

    - name: Release Tests
      run: make test -C ./build ARGS='--output-on-failure'

  gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Debug Compile
      run: |
        mkdir build
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -S . -B ./build
        make --directory ./build -j

    - name: Debug Tests
      run: make test -C ./build ARGS='--output-on-failure'
    
    - name: Clean Build
      run: |
       rm -rf ./build/

    - name: Release Compile
      run: |
        mkdir build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -S . -B ./build
        make --directory ./build -j

    - name: Release Tests
      run: make test -C ./build ARGS='--output-on-failure'

  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install lcov 2.x
      run: |
        sudo apt-get install -y libcapture-tiny-perl libdatetime-perl
        git clone --branch v2.3 --depth 1 https://github.com/linux-test-project/lcov.git /tmp/lcov
        sudo make -C /tmp/lcov install

    - name: Debug Compile
      run: |
        mkdir build
        cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON -S . -B ./build
        make --directory ./build -j

    - name: Debug Tests
      run: make test -C ./build ARGS='--output-on-failure'

    - name: Get Coverage
      run: |
        lcov --ignore-errors inconsistent,unused --directory ./build/ --capture --output-file coverage.info
        lcov --ignore-errors inconsistent,unused --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
        lcov --ignore-errors inconsistent,unused --remove coverage.info '*/gtest/*' "${HOME}"'/.cache/*' --output-file coverage.info
        lcov --ignore-errors inconsistent,unused --list coverage.info

    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash) -f coverage.info